### ISSUE TITLE
Objekt in Editor automatisch zentrieren. Centroid zum Ursprung verschieben, controls auch dort zentrieren. Generell die Controls immer wieder zum Ursprung zurückschieben, also nach jeder Transformation?

### ISSUE THREAD

**Issue by sophie-sudoku** [ErlerPhilipp/Pix2Model#60]

**Comment by sophie-sudoku** [comment]
@ErlerPhilipp can we discuss this in the next meeting? the controls are currently always in the center of the object. if we put them in the center of the coordinate system, then the pivot for rotation changes and rotating and scaling becomes more couter intuitive i guess. we can think about giving the user the option, to toggle between global and local transformations maybe

**Comment by ErlerPhilipp** [comment]
yes, let's discuss it in the next meeting.

the root of this idea is that i had an example where the actual object was far from the bounding box center so that the controls were off screen initially.

maybe, it's sufficient to center the point clouds and meshes with the center of mass instead of center of BB.

**Comment by sophie-sudoku** [comment]
adjust zoom initially, such that the whole object is visible (shortcut F for framing)
